DATA_SPLIT_TRAINING: 0.75
DATA_SPLIT_TEST: 0.2
DATA_SPLIT_PLAY: 0.05

DATA_NAME_TRAINING: './data/training_raw.pickle'
DATA_NAME_TEST: './data/test_raw.pickle'
DATA_NAME_PLAY: './data/play_raw.pickle'

DATA_NUM_CLASSES: 10
DATA_NUM_VALIDATION: 100
NUM_SIMILAR_RETURNED: 5
VALIDATION_RESULTS_PATH: './data/validation_results.pickle'


# range 0 -> 1 is the error tolerance uniform vectors, normalized amount of tolerable deviation from the means
UNIFORM_DISTRIBUTION_TOLERANCE: 0.10


RUN_HISTOGRAM_FEATURE_EXTRACT: False
HISTOGRAM_FEATURE_PATH_TRAINING: './data/featuresHistogram.pickle'
HISTOGRAM_FEATURE_PATH_TEST: './data/featuresHistogramTest.pickle'
HISTOGRAM_BUCKET_RESOLUTION: 30

RUN_CONVNET_FEATURE_EXTRACT: False
CONVNET_FEATURE_PATH_TRAINING: './data/featuresConvnet.pickle'
CONVNET_FEATURE_PATH_TEST: './data/featuresConvnetTest.pickle'
CONVNET_MODEL_PATH: './data/convnetModel.pickle'
CONVNET_TRAIN_EPOCHS: 5
CONVNET_BATCH_SIZE: 128

RUN_LBP_FEATURE_EXTRACT: False
LBP_FEATURE_PATH_TRAINING: './data/featuresLbp.pickle'
LBP_FEATURE_PATH_TEST: './data/featuresLbpTest.pickle'
LBP_BUCKET_RESOLUTION: 30
LBP_RADIUS: 3
LBP_POINTS: 8